"""initial schema

Revision ID: 0cf1c6a45a03
Revises: 
Create Date: 2025-06-12 16:33:50.155765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf1c6a45a03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_directory_key'), 'users', type_='unique')
    op.drop_column('users', 'directory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('directory', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_directory_key'), 'users', ['directory'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
